RT-343: Implement Activity Streams 2.0 feed for extracting data
uktrade/update-supply-chain-information pull request #148
Opened 2021-07-09 15:29 UTC by NickFitz

Also addresses other tickets, or parts thereof; is part of RT-108.

2021-07-15 10:24 UTC, dev-digital requested changes
Mostly questions and minor comments

2021-07-15 10:24 UTC, dev-digital commented on update_supply_chain_information/activity_stream/models.py
> +class ActivityStreamQuerySetWrapper:
Why is this not derived from queryset and then over-riding as per our requirements ?
Would we still need to handle _getattr_

2021-07-15 11:53 UTC, NickFitz commented on update_supply_chain_information/supply_chains/management/commands/ingest_csv.py
> +                row["last_modified"] = datetime.now().strftime(r"%Y-%m-%dT%H:%M:%S.%f")
I'll check.

2021-07-15 12:38 UTC, NickFitz commented on .github/workflows/run-tests.yaml
> +      HAWK_SECRET_ACCESS_KEY: 'wk2l6OBYRVnyCYq3S9n3Y8IQ0i2M4e8o'
They're the values for development, though I'll generate proper versions for use in production. I'll see what the options are for providing such values to GitHub Actions.

2021-07-15 13:02 UTC, NickFitz commented on update_supply_chain_information/supply_chains/test/test_activity_stream.py
> +pytestmark = pytest.mark.django_db
Yes, left over from before I realised it made more sense to put the AS stuff in its own app.

2021-07-15 13:15 UTC, NickFitz commented on update_supply_chain_information/supply_chains/management/commands/ingest_csv.py
> +                row["last_modified"] = datetime.now().strftime(r"%Y-%m-%dT%H:%M:%S.%f")
The `last_modified` column is included in the generated CSV, in the format `2021-05-31T23:00:00Z` which should be ingestible as it's a standard ISO format. But when I try to use `ingest_csv` to read the generated file (in a dump of supply chains), it fails before it gets that far, on `last_submission_date` as the date in the generated file is `1976-12-26` but the script wants it to be `1976/12/26`.

2021-07-15 13:24 UTC, NickFitz commented on update_supply_chain_information/supply_chains/models.py
> +        null=True, blank=True, unique=True, max_length=MAX_SLUG_LENGTH
Looking back through Data Vis devs chat to the date of the change, it was something we discussed the day before (8 June) as being desirable because the Supply Chain slug is the top level of the URL so has to be unique, otherwise it's impossible to know which supply chain to display. I don't think `name` has to be unique; there was some chat about the possibility of two departments each getting ceramics or something, but that was deemed unlikely (IIRC). I think that change just ended up in here because I was modifying that file at the time, to add the `last_modified` fields.

2021-07-15 13:27 UTC, NickFitz commented on update_supply_chain_information/activity_stream/test/conftest.py
> +    return SupplyChainFactory()
Difficult to think of an alternative name for it though. Better, I think, to make the places that currently create their own use that fixture; if any of them need for some reason to create their own, that can be given a more meaningful name that makes it clear why the fixture isn't being used.

2021-07-15 13:50 UTC, NickFitz commented on update_supply_chain_information/activity_stream/test/conftest.py
> +def wrapped_union_queryset(bit_of_everything_queryset) -> ActivityStreamQuerySetWrapper:
Changing it involves changing so many other things that I'm going to leave it for now (after spending over twenty minutes on it and getting new test failures popping up everywhere). It may not return anything meaningful, but it depends on a chain of other fixtures, many of which end up being used in their own right elsewhere, so turning it into a function would involve duplicating all that code. That would then mean having to check both places if things needed changing later for some reason.

2021-07-15 13:51 UTC, NickFitz commented on update_supply_chain_information/activity_stream/viewsets.py
> +        super().__init__(*args, **kwargs)
That was left over as a place to add a breakpoint so I could work out how the base DRF class worked. I've removed it.

2021-07-15 13:52 UTC, NickFitz commented on update_supply_chain_information/activity_stream/test/test_viewsets.py
> +        self, wrapped_union_queryset
Yes, I forgot about `sample.env`. I've added the required fields in there.

2021-07-15 13:55 UTC, NickFitz commented on update_supply_chain_information/activity_stream/test/test_viewsets.py
> +        self, wrapped_union_queryset
There won't be anything in the QuerySet but a single instance of `GovDepartment`, but yes, that doesn't really matter in this case as we just want to know that the method is returning an instance of the wrapper class, so I've removed it.

2021-07-15 14:06 UTC, NickFitz commented on update_supply_chain_information/activity_stream/test/util/hawk.py
> +from base64 import (
This is used to generate an Authentication header in the same way as the one sent by Activity Stream, returned by the fixture `hawk_authentication_header`. As that header is used for testing that the authentication code is properly validating it, and that the viewset is properly restricting access based on it, I think it's important that it has a real, valid header to check.

2021-07-15 14:09 UTC, NickFitz commented on update_supply_chain_information/activity_stream/serializers.py
> +    name = ""
No, that's from when there were various subclasses for serialising the different models, which supplied the correct values for it. Since I worked out how to serialise anything without needing the subclasses, it's no longer used.

2021-07-15 14:11 UTC, NickFitz commented on update_supply_chain_information/activity_stream/serializers.py
> +    def update_foreign_keys(self, foreign_keys, object_representation):
I've changed `update_foreign_keys` and `_build_item_id` as yes, they're internal methods.

2021-07-15 14:14 UTC, NickFitz commented on update_supply_chain_information/activity_stream/test/conftest.py
> +def strategic_action_queryset(last_modified_times) -> StrategicActionQuerySet:
It depends on the `last_modified_times` fixture that's used a lot elsewhere, has other fixtures that depend on it, and is used as a fixture in its own right in a lot of tests.

2021-07-15 14:16 UTC, NickFitz commented on update_supply_chain_information/activity_stream/test/test_serializer.py
> +        supply_chain_id = strategic_action.supply_chain_id
Not sure what you mean?

2021-07-15 14:19 UTC, NickFitz commented on update_supply_chain_information/activity_stream/serializers.py
> +                        for related_item in related_item
The main case, and the only one that's currently used, is the above one where it's a foreign key; we don't have any ManyToMany fields (or not yet), when it would be a list of keys. I'll change it to make it clearer what's happening 😁

2021-07-15 14:21 UTC, NickFitz commented on update_supply_chain_information/activity_stream/serializers.py
> +                    # reverse ForeignKey and ManyToMany relationships have multiple keys
Not yet, but I included that so that if we do end up with any, it's at least got a code path to follow. It might even work ;-)

2021-07-15 14:26 UTC, NickFitz commented on update_supply_chain_information/activity_stream/authentication.py
> +            etype, val, tb = sys.exc_info()
Apparently not. Virtually all of this code was just copied from Hawkrest, which does what we need but fails on the Django WSGI server as it automatically adds a `text/plain` Content-Type header if none or a blank one is sent, and Activity Stream sends a blank one. Hence I've added a few lines above to check for that, as otherwise I couldn't authenticate my local Activity Stream's requests, which was necessary to get things working.  I've changed it to underscore.

2021-07-15 14:29 UTC, NickFitz commented on update_supply_chain_information/activity_stream/authentication.py
> +            log.debug(traceback.format_exc())
Again, part of Hawkrest. The `debug` lines won't appear on production, but I think the `warning` level one would be useful to have in our logs in case AS was failing to authenticate. If updates to our our data stopped appearing in AS, that would be one of the first things to check.

2021-07-15 14:31 UTC, NickFitz commented on update_supply_chain_information/activity_stream/authentication.py
> +        request.META["hawk.receiver"] = receiver
I think that refers specifically to the Authentication request header; I'm no expert on authentication middleware, so I'm not sure exactly what it does.

2021-07-15 14:36 UTC, NickFitz commented on update_supply_chain_information/activity_stream/test/test_authentication.py
> +class TestHawkAuthentication:
DRF's `DEFAULT_AUTHENTICATION_CLASSES` setting specifies `ActivityStreamHawkAuthentication`, and DRF calls into that for authentication when it receives a request.

2021-07-15 14:37 UTC, NickFitz commented on update_supply_chain_information/activity_stream/test/test_authentication.py
> +                f"{endpoint}", HTTP_AUTHORIZATION=hawk_authentication_header
Yes, it uses GET requests with a Hawk authentication header.

2021-07-15 14:43 UTC, NickFitz commented on update_supply_chain_information/activity_stream/pagination.py
> +        return self.summary
This comes from Data Hub's code. The `summary` is required by W3C's Activity Streams 2.0 specification IIRC. Looking back at DH's code, they have multiple subclasses of their base Pagination class so need to ensure the `summary` attribute is set. As we don't, and it's only used in one place, I think I can get rid of this method altogether.

2021-07-15 14:45 UTC, NickFitz commented on update_supply_chain_information/activity_stream/test/test_pagination.py
> +    def test_last_page_has_next_page(self, wrapped_union_queryset, rf):
Request factory: https://pytest-django.readthedocs.io/en/latest/helpers.html#rf-requestfactory

2021-07-15 14:50 UTC, NickFitz commented on update_supply_chain_information/activity_stream/test/test_activity_stream_endpoint.py
> +            with mock.patch(
I'm not sure how to mock something at class level that depends on supplying a return value derived from a fixture within individual test methods.

2021-07-15 15:03 UTC, NickFitz commented on update_supply_chain_information/activity_stream/test/test_activity_stream_endpoint.py
> +                    next_page_path = f"{next_page_path}?{url_parts.query}"
We should have been; the above test was passing for the wrong reasons :rofl

We need to parse the URL as the Hawk header on the receiver is recreated using only the path, while `next_page_link` is a full URL with scheme and domain. The previous test is checking only that there was no "next" in the received JSON, and there wasn't because all it contained was an authentication error, as the request header incorrectly used that full URL and was thus rejected by the receiver. I've added the URL parsing up there too so it builds a valid header, and added a check on all responses for 200 OK before going on to the checks of the content.

2021-07-15 15:10 UTC, NickFitz commented on update_supply_chain_information/activity_stream/models.py
> +            models += app_models
I don't think it makes much difference, but I can change it if you wish :-)

2021-07-15 15:11 UTC, NickFitz commented on update_supply_chain_information/activity_stream/models.py
> +        #     yield model.objects.for_activity_stream()
Yes, another leftover from experimenting with an alternative approach which turned out not to be necessary.

2021-07-15 15:14 UTC, NickFitz commented on update_supply_chain_information/activity_stream/models.py
> +        N.B. default value will cause failure if used on dates from BCE
Before the Common Era, i.e. earlier than 1/1/1 in the Gregorian calendar. I'm hoping we don't end up dealing with any data for which that's a problem ;-)

https://en.wikipedia.org/wiki/Common_Era

2021-07-15 15:19 UTC, NickFitz commented on update_supply_chain_information/activity_stream/test/test_pagination.py
> +            return_value=int(page_length),
Yes, not sure what that was doing in there 🤣

2021-07-15 15:35 UTC, NickFitz commented on update_supply_chain_information/activity_stream/models.py
> +class ActivityStreamQuerySetWrapper:
If it was derived from QuerySet the `__getattr__` method wouldn't be called; it's only called for attributes that the thing doesn't have.

So if, for example, one invoked `count()` on it, the base method would be called and just fall over as it wouldn't know it was supposed to delegate to the real QuerySet in `_queryset`. Similarly for other properties and methods. By deliberately not making it an instance of QuerySet, and then providing an implementation of `__getattr__` that knows how to delegate to the wrapped QuerySet, it ends up behaving like the wrapped QuerySet except for those bits we  handle specially (`order_by` and `filter`, and `__getitem__` to support slicing).

It would be possible to derive it from QuerySet and then override `__attr__` to intercept the things we're interested in, but I reckon that would be even more complicated and hard to understand. Probably also a lot easier to break something in horrible ways 😨 

I'm also not sure how `__getitem__` would then work; at the moment, we can just delegate by slicing the wrapped queryset, but if you look at the QuerySet implementation of `__getitem__` it's terribly complicated.

2021-07-16 09:44 UTC, dev-digital commented on update_supply_chain_information/activity_stream/authentication.py
> +            log.debug(traceback.format_exc())
>The debug lines won't appear on production

Is it enforced from our settings ?

irrespective, moving to _warning_ sounds good to me as it would potentially break the data pipeline

2021-07-16 09:45 UTC, dev-digital commented on update_supply_chain_information/activity_stream/authentication.py
> +        request.META["hawk.receiver"] = receiver
Was this line taken from other AS down stream repos, then ?

2021-07-16 09:47 UTC, dev-digital commented on update_supply_chain_information/activity_stream/models.py
> +        N.B. default value will cause failure if used on dates from BCE
First thing I did while reviewing is to look for MIN and MAX for _datetime.datetime_
apparently you have picked MIN value :+1:

2021-07-16 09:56 UTC, dev-digital commented on update_supply_chain_information/activity_stream/test/conftest.py
> +    return SupplyChainFactory()
Not sure, If I follow it fully but given that fixture is used _just_ once and its a one liner, I would remove the fixture itself rather than rename.

2021-07-16 10:15 UTC, dev-digital commented on update_supply_chain_information/activity_stream/test/conftest.py
> +def wrapped_union_queryset(bit_of_everything_queryset) -> ActivityStreamQuerySetWrapper:
>after spending over twenty minutes on it and getting new test failures popping up everywhere

yes, these makes code brittle which is bad for maintenance.

Most likely, these will be picked up when we bring in #154 (which I am planning to address shortly)

2021-07-16 10:50 UTC, dev-digital commented on update_supply_chain_information/activity_stream/test/test_activity_stream_endpoint.py
> +            with mock.patch(
Agree, we can't call [fixtures](https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly) directly 

However I can ask the need for both fixtures to be a fixture at the first place :grinning:

2021-07-16 11:15 UTC, dev-digital commented on update_supply_chain_information/supply_chains/models.py
> +        null=True, blank=True, unique=True, max_length=MAX_SLUG_LENGTH
The way it(our chat) ended as I remember was, we needed confirmation from shan.
Reason for original comment is/was slug is directly derived from name. If name is not unique, slug wouldn't be.

Having said that, I will not go look for trouble. Lets keep things as they are and hope they work :crossed_fingers:

2021-07-16 13:27 UTC, dev-digital commented on update_supply_chain_information/activity_stream/models.py
> +class ActivityStreamQuerySetWrapper:
Now the chosen method looks attractive :smile:

2021-07-16 13:31 UTC, dev-digital commented on update_supply_chain_information/activity_stream/README.md
> +# Activity Stream
This is very helpful. One change I would recommend is to move this file to somewhere like $root/docs/activity_stream.md so that its easy to find.

2021-07-16 14:10 UTC, NickFitz commented on update_supply_chain_information/activity_stream/README.md
> +# Activity Stream
I was thinking in terms of it being able to move with the code, as the app itself has potential for being used in other projects - the only dependencies it has on the other parts of the app (`supply_chains` and `accounts`) are in the tests. Maybe add a docs directory with a README and link to it from there, or link to it from the main README?

Having it here also means it's displayed in GitHub when browsing this subdirectory.

2021-07-16 15:25 UTC, dev-digital commented on update_supply_chain_information/activity_stream/README.md
> +# Activity Stream
That's fine, then.

2021-07-19 07:53 UTC, dev-digital commented on update_supply_chain_information/supply_chains/management/commands/ingest_csv.py
> +                row["last_modified"] = datetime.now().strftime(r"%Y-%m-%dT%H:%M:%S.%f")
That's correct, almost. Script want the format to be MM/DD/YY(eg: 8/1/20) which is what we have within historic csv data.

Coming back to the original comment, as long as it comes out in recognised format(which is the case), we are good. Only time we use _ingest_csv_ is while feeding in the historic data(in csv format). 
If we really want to extract and re-ingest, we would use JSON format.

2021-07-19 08:02 UTC, NickFitz commented on update_supply_chain_information/activity_stream/test/conftest.py
> +    return SupplyChainFactory()
It's now used in several places :)

2021-07-19 08:04 UTC, dev-digital commented on update_supply_chain_information/activity_stream/test/test_serializer.py
> +        supply_chain_id = strategic_action.supply_chain_id
Just wanted to know if Left Hand Side of L15 would be field SupplyChain.id (which I believe the case)

2021-07-19 08:04 UTC, NickFitz commented on update_supply_chain_information/activity_stream/authentication.py
> +        request.META["hawk.receiver"] = receiver
No, it's from a third-party library for enabling Hawk authentication in Django REST Framework.

2021-07-19 08:52 UTC, dev-digital approved these changes
Nice work,Nick :+1: 
It was good read.

2021-07-19 13:56 UTC, merged