RT-195: Refactor/home text
uktrade/update-supply-chain-information pull request #67
Opened 2021-05-27 15:32 UTC by dev-digital

**New content**

##### For in-complete submissions

You need to complete your monthly update. Complete (x) supply chains by Friday 22 January 2021.

##### For completed submissions

Your monthly update is complete. All supply chains have been completed for this month.

**Changes**
- Update summary as per latest content
- Tests

2021-05-27 15:34 UTC, NickFitz approved these changes
👍

2021-05-27 16:25 UTC, mforner13 requested changes

2021-05-27 16:25 UTC, mforner13 commented on defend_data_capture/supply_chains/templates/index.html
> +                You need to complete your monthly update. Complete <strong>{{ num_in_prog_supply_chains }} supply chains</strong> by
I think when Sally wrote 'Complete your monthly update' and 'Your monthly update is complete' she was referring to the header text, rather than saying to add this text to the bullet point :) (Like in pic below)

![Screenshot 2021-05-27 at 17 23 59](https://user-images.githubusercontent.com/22460823/119862372-56b4bf00-bf10-11eb-8578-9f6f58c0282e.png)

2021-05-28 09:58 UTC, mforner13 commented on defend_data_capture/supply_chains/templates/index.html
> +            </li>
Did Sally say we can remove this bit? :)

2021-05-28 10:07 UTC, mforner13 commented on defend_data_capture/supply_chains/templates/index.html
> +            </li>
Scrap that 😋

2021-05-28 10:09 UTC, mforner13 approved these changes
👍

2021-05-28 10:34 UTC, NickFitz approved these changes
👍

2021-05-28 10:40 UTC, merged